[tool.poetry]
name = "roman-calculator"
version = "0.1.0"
description = "A calculator that works with Roman numerals."
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.0"
pytest-cov = "^2.11"